-- SQL schema for TRADINGGROW self-hosted MySQL database
-- Import this file into phpMyAdmin or MySQL on Hostinger.

CREATE DATABASE IF NOT EXISTS `igrowdb` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `igrowdb`;

CREATE TABLE IF NOT EXISTS `master_connections` (
  `vantage_id` VARCHAR(64) NOT NULL,
  `server` VARCHAR(128) NOT NULL,
  `is_connected` TINYINT(1) NOT NULL DEFAULT 0,
  `last_heartbeat` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`vantage_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `signals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `currency_pair` VARCHAR(16) NOT NULL,
  `direction` ENUM('BUY','SELL') NOT NULL,
  `entry_price` DECIMAL(18,8) NOT NULL DEFAULT 0,
  `stop_loss` DECIMAL(18,8) NOT NULL DEFAULT 0,
  `take_profit` DECIMAL(18,8) NOT NULL DEFAULT 0,
  `status` VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  `source` VARCHAR(64) NOT NULL DEFAULT 'app',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `followers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `follower_key` VARCHAR(128) NOT NULL,
  `signal_id` BIGINT UNSIGNED NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  `last_seen` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX (`signal_id`),
  CONSTRAINT `fk_followers_signal` FOREIGN KEY (`signal_id`) REFERENCES `signals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `bridges` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `service` VARCHAR(64) NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'ONLINE',
  `latency_ms` INT UNSIGNED NOT NULL DEFAULT 0,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ledger_entries` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(128) DEFAULT NULL,
  `signal_id` BIGINT UNSIGNED DEFAULT NULL,
  `amount` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `type` VARCHAR(32) NOT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX (`signal_id`),
  CONSTRAINT `fk_ledger_signal` FOREIGN KEY (`signal_id`) REFERENCES `signals` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
